name: Node.js CI

on:
  push:
    branches: ["prod"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Update npm
        run: |
          export NPM_INSTALL_DIR=$(npm prefix -g)
          export PATH="$NPM_INSTALL_DIR/bin:$PATH"
          npm install -g npm@latest

      - name: Display npm version
        run: npm --version

      # Rest of your workflow steps...
